### PR TITLE
Minifacebook video will play from the time the original is paused.

### PR DESCRIPTION
**Pull request by dhirajbodicherla**
Get the current time from original video and set time on minivideo.
Worked well on 360, hd, sd

### CODE REVIEW

**Comment by dhirajbodicherla** [comment]
If you're planning to merge this, please do not do it right now. I will cherry-pick this feature alone and merge a branch instead of master!

**Comment by jianweichuah** [comment]
I actually tried this out myself yesterday!
My only concern was that because they're 2 different videos, say when a user decides to switch to mini screen after watching the video for 20 minutes, the mini screen will take a significant time to reload up to the 20 minute mark.
I'm thinking if we wanna do this, we should also add a loading icon when the video is being loaded so that it's clear that it's loading and not broken or lagging.

**Comment by dhirajbodicherla** [comment]
Agreed! This is one of the long HD videos that I know of https://www.facebook.com/zuck/videos/vb.4/10102371249389011. It does take about 2-3 seconds to load the video and start from a particular time. Loading icon sounds like a good idea. Lets give that a shot.

**Comment by dhirajbodicherla** [comment]
Not going ahead with this feature for now.

**Pull request closed without merging**
